### ISSUE TITLE
Importing the numpy C-extensions failed.

### ISSUE THREAD

**Issue by joamatab** [KLayout/klayout#1036]
Hi,

Im trying to use some klayout plugins that require numpy so when i start klayout i get some errors

I think the issue is coming from installing the Ubuntu klayout from the website (probably built with python3.8)
and trying to run in Debian (where im using pyhton3.9)

![image](https://user-images.githubusercontent.com/4514346/158644654-2ef4e059-2f80-421d-a26d-d1b3d94a7828.png)

How could choose the python interpreter inside klayout?
Im trying to avoid building it from source :)

**Comment by ejprinz** [comment]
You should import the klayout module using pip3 in Debian instead of
installing a version built for a different OS.

pip3 install klayout
should do it.

**Comment by joamatab** [comment]
Thank you Erwin @ejprinz 

`pip3 install klayout` works well when using klayout python standalone library

however the macros are using the built-in python interpreter inside klayout, and that's where the numpy errors are coming from

How could we choose the path for the python interpreter to run the macros from the klayout GUI?
in my case i would like that to be `/home/jmatres/mambaforge/bin/python`

**Comment by ejprinz** [comment]
I don't think you can expect a Ubuntu package to work on Debian.

I think the best option in this case is to just download the source code
and recompile it on Debian. I have a similar issue where I have to compile
for a unique configuration of Linux. So I usually handle this as follows:
* Download klayout-0.27.8.tar.gz from the KLayout download page.
* tar -zxf klayout-0.27.8.tar.gz
* cd klayout-0.27.8
Run this build script in the klayout source directory:
./build.sh \
    -qt${qt_version}  \
    -qmake ${qt_used}/bin/qmake \
    -python ${python_used}/bin/python3 \
    -pylib  ${python_used}/lib/libpython${python_major_version}.so \
    -pyinc  ${python_used}/include/python${python_major_version} \
    -ruby ${ruby_used}/bin/ruby \
    -option -lutil \
    -prefix ${prefix} \
    -with-64bit-coord \

You can get the options from:
./build.sh --help
Usually for non-Debian package installs people use /usr/local as the
prefix, not /usr.
You need to find the various pieces (my environment variables ${...}), in
Debian this should be pretty easy.
Also since Ubuntu is derived from Debian, you can follow the Ubuntu
instructions, so you do
* sudo apt install build-essential gcc make g++ libqt4-dev-bin libqt4-dev
ruby ruby-dev python3-dev libz-dev

Another way is to install Ubuntu and use the provided package ;-)

For Ubuntu (these instructions should also work on Debian):

   - C++ toolchain: gcc, g++ and make
   - Qt including development tools: libqt4-dev-bin and libqt4-dev
   - Ruby: ruby and ruby-dev
   - Python: python3 and python3-dev
   - zlib: libz-dev

The compilation takes a while (~10min to 1hr). If this works you can even
run KLayout on a Chromebook.

So this way you can use whatever Python you want from your OS. Since Debian
is pretty much the baseline for the build system you should be able to do
it easily. Of course you need to install the usual Debian build-essential
package and whatever else is needed, like qt5. Also always install the
<pkg>-devel packages too as they contain the header files.

Disclaimer: I haven't actually tried it on Debian as I run Windows with
WSL, RedHat EL7, and Debian 20.04 on a server.

Good luck.

**Comment by atait** [comment]
I don't think you can switch the interpreter because klayout has its own bindings that were built for that version of the interpreter. What you can change is numpy.
```python
python38 -m pip install numpy lygadgets
python38 -c "from lygadgets.salt_linker import link_any; link_any('numpy')"
```
where `python38` is some 3.8 executable, any 3.8 executable. The first line will get the Debian wheels you need. The second will put it on klayout's pythonpath.

**Comment by klayoutmatthias** [comment]
Thanks for all these hints!

@joamatab I don't understand how you were even able to install the Ubuntu .deb package. I tried with a Docker image of debian/latest and did not get further because libpython3.8 could not be satisfied.

KLayout builds against the system interpreter, which means that you can install numpy with pip3 and KLayout will see it. But with Python 3.9 as system interpreter and KLayout building against 3.8 this will not work.

Building from source isn't that difficult. Unless there is an official (and up to date) Debian package, this is the only option to install KLayout for all distributions. Here is a tested recipe for a debian/latest Docker image (as root):

```
apt-get update -y
apt-get install -y qtbase5-dev gcc g++ make libz-dev qttools5-dev libqt5xmlpatterns5-dev qtmultimedia5-dev libqt5multimediawidgets5 libqt5svg5-dev ruby ruby-dev python3 python3-dev pip wget
wget https://www.klayout.org/downloads/source/klayout-0.27.8.tar.gz
tar hzxvf klayout-0.27.8.tar.gz 
cd klayout-0.27.8
./build.sh -j4 -bin /usr/local/bin/klayout      # 4 cores
pip3 install numpy
```

This is a short test script:

```
import numpy
import pya

print(pya.Box(1, 2, 3, 4))
print(numpy.array([1, 2, 3]))
```

which runs with klayout this way:

```
/usr/local/bin/klayout/klayout  -b -r script.py
```

and gives:

```
(1,2;3,4)
[1 2 3]
```

Matthias

**Comment by joamatab** [comment]
Thank you Alex and Matthias,

both of your solutions worked

1. building it from source
2. adding numpy with lygadgets

There is third solution that provides a conda installation of klayout GUI (currently works only on linux, python3.8, and has no ruby support) 

https://github.com/flaport/condalayout

**Comment by klayoutmatthias** [comment]
Very good. I'll close this ticket for now.
