### ISSUE TITLE
strmxxx only needs to reads lef + map once, not again and again for each def file

### ISSUE THREAD

**Issue by stefanottili** [KLayout/klayout#1038]
lef + map can only be specified once for all def files, so only read them once.

**Comment by klayoutmatthias** [comment]
That's unfortunately inherent in the architecture: the "+" operator joins the results of something delivered by an abstract reader (that's why the components can be anything) and the abstract readers do not know of each other. Every single item is read individually. As LEF+map is some ingredient to DEF, they are read for separately for each component.

**Comment by stefanottili** [comment]
Oh well, 
unfortunate architecture I guess, so be it reading lef is fast … 
But reading it over and over again is still a waste of time.
