### ISSUE TITLE
Only show existing files for File->Open Recents

### ISSUE THREAD

**Issue by stefanottili** [KLayout/klayout#1131]
It would be nice if File->Open Recents would only list files that still exist when this menu get's opened.

**Comment by stefanottili** [comment]
It would be nice if File->Open Recents would only list files that still exist when this menu get's opened.

**Comment by Kazzz-S** [comment]
I agree with you.
I am solving this issue with my homemade macros [SamplePYAmacros.zip](https://github.com/KLayout/klayout/files/9224099/SamplePYAmacros.zip), as shown below.
This approach can apply to other "Recent..." including the layer properties, sessions, and bookmarks.

Just for your reference.
Kazzz-S

----

1. I have already deleted "Abacus.oas"
![A](https://user-images.githubusercontent.com/16847255/181865134-f9c98e4e-a04a-4666-bcd2-94ecb93333e8.png)
2. Hence, open error
![B](https://user-images.githubusercontent.com/16847255/181865142-7809cf64-f4b5-431e-b0fe-f054b186bf1b.png)
3. Let's check the existence
![C](https://user-images.githubusercontent.com/16847255/181865149-b17655e7-1d6b-41ff-ac6f-050fa12b51ef.png)
4. Updated the list
![D](https://user-images.githubusercontent.com/16847255/181865157-789639b3-63a4-4d6b-aafb-db53847fbae7.png)
5. Clean up
![E](https://user-images.githubusercontent.com/16847255/181865159-00e5d746-2b2c-4c8d-bd0a-a06da1deddea.png)
![F](https://user-images.githubusercontent.com/16847255/181865164-72c62fd4-afa1-4f5f-abf1-3efded34a4bc.png)

Undo and Redo are not possible.

**Comment by Kazzz-S** [comment]
@klayoutmatthias,

I'd like to know how to show the added macro menus at the bottom of the side file list.
![G](https://user-images.githubusercontent.com/16847255/181866151-3ed1b950-01f4-4dd7-8f7c-9991bc08b3a4.png)

Warm regards,
Kazzz-S

**Comment by klayoutmatthias** [comment]
@kazzz Adding menu items to these menus is not possible currently as these menus are created dynamically and before that, all items are cleared :(

Nevertheless I have implemented a fix for this ticket. As of now, non-existing files are grayed out rather than hidden. I found this slightly more intuitive as it conveys more information. In addition, there is no interference with the logic that limits the number of entries in each MRU list - if a file is only temporarily unavailable, it will not be deleted entirely, but will show up as enabled again.

I have also implemented a "clear list" menu item at the end of the list. There is no undo available for this function, but I hope, users know what they are doing :)

There has been much development in that area for the Qt-less Python module, so I'm afraid the feature will not make it into the 0.27 branch.

Best regards,

Matthias

**Comment by Kazzz-S** [comment]
@klayoutmatthias,

Thank you for your prompt enhancement work. I like your idea. 
I can shorten the enlarged menu lists.
![H](https://user-images.githubusercontent.com/16847255/182046984-22eebd9b-076f-49a4-980d-88f5cd1a16cb.png)

Warm regards,
Kazzz-S

**Comment by stefanottili** [comment]
clear list doesn't seem to be persistent.
clear list, close klayout, run klayout again, all the cleared files are back.

**Comment by klayoutmatthias** [comment]
My fault. Did not write the configuration properly. 

(did not exit either, because I did not want to spoil my recent file list :) )

Patched master as the PR is already merged.
