### ISSUE TITLE
Basic string: construction from Null is not valid

### ISSUE THREAD

**Issue by joamatab** [KLayout/klayout#1176]
How can we remove `Basic string: construction from Null is not valid` when modifying Klayout Pcells?

![image](https://user-images.githubusercontent.com/4514346/199085501-158027af-8408-4cbf-af77-bf088fad227d.png)

We saw this when wrapping gdsfactory Pcells in klayout
https://github.com/gdsfactory/gdsfactory/issues/800

However we noticed it also happens with klayout builtin PCells

**Comment by klayoutmatthias** [comment]
Could you try whether this is fixed with master? Master builds can be downloaded here: https://www.klayout.org/downloads/master/

I can release some 0.27.12 version with the patch for #1164, but the message is pretty generic. There are many reasons for this error.

If this problem can still be reproduced on master, maybe you can give me a hint how to reproduce it.

Matthias

**Comment by joamatab** [comment]
Hi Matthias,

The release from master works perfectly without any issues

thank your for your help

**Comment by joamatab** [comment]
Thank you Matthias!
