### ISSUE TITLE
NetTracerTechnology changed to NetTracerConnectivity in 0.28

### ISSUE THREAD

**Issue by ejprinz** [KLayout/klayout#1223]
I am calling the NetTracerTechnology from Python. It looks like in 0.28 the name and maybe API has changed to NetTracerConnectivity. So I need the following code to make my scripts run again:

``` python
KLayout_Version = subprocess.run(Path(os.getenv('bin') + '/klayout_version'),
                                 text=True, capture_output=True).stdout

if re.search('28', KLayout_Version):
    net_tracer_tech = kl.NetTracerConnectivity()
else:
    net_tracer_tech = kl.NetTracerTechnology()

```

This should be documented, as well as other API changes in 0.28.

**Comment by klayoutmatthias** [comment]
That came with the implementation of multi-stack support for net tracer. A technology object now has to support multiple stacks, hence two classes are required.

I have added a comment to the release notes. Thanks for bringing this up.

For detecting the correct class, I'd suggest to use this scheme which is independent on the KLayout version string:

```
net_tracer_tech = (kl.NetTracerConnectivity if "NetTracerConnectivity" in kl.__all__ else kl.NetTracerTechnology)()
```

I also would like to advertise the `LayoutToNetlist` class which is the basis of the LVS feature. This class provides a more efficient algorithm and supports fast hierarchical extraction of huge nets. This class is not an auxiliary algorithm like `NetTracerConnectivity` but a main feature of KLayout and is less likely to change. You can extract all nets in a single pass and then use "probe" to pick a certain net, "build_nets" to extract the shapes etc. Maybe you want to consider using this feature rather than the net tracer. Only with hierarchical-mode `LayoutToNetlist` there is a chance to extract power nets of large designs in reasonable time.

Matthias
