### ISSUE TITLE
Python error messages should include more information

### ISSUE THREAD

**Issue by simonwaid** [KLayout/klayout#1237]
I'm trying to write a PCell using the integrated editor. 

Of course I make mistakes. From other development tools (eclipse with PyDev) I'm used to get error messages from python that point me the location of the mistake. 

In Klayout I get error messages such as:
```
ERROR: syntax error (class SyntaxError)
ERROR: argument 2 must be sequence of length 4, not 6 (class TypeError)
```

No information about which line is affected. It is very, very painful to debug code like that.

**Comment by klayoutmatthias** [comment]
No, that is not true in general:

![image](https://user-images.githubusercontent.com/25720841/210151442-1698e789-d226-4f02-a42b-c98ff1d37e1c.png)

So there is a specific situation that will not give you the line number. Please indicate more precisely how to reproduce the problem and I will see what I can do.

**Comment by lukasc-ubc** [comment]
@simonwaid maybe the debugging mode is not enabled in your case?

**Comment by klayoutmatthias** [comment]
Even outside the debugger, the message should be detailed as shown above.

Either that request refers to an older version or the mentioned behaviour is specific to a certain use case. Specifically during PCell code execution, error messages are handled differently. But I cannot imagine syntax errors happen in that phase - you need to load code before the PCell gets executed. And syntax errors should be seen during that phase already.

Matthias

**Comment by simonwaid** [comment]
Here is a minimal example:
```
import pya

class PCellLib(pya.Library)

  def __init__(self):
    pass  
    
PCellLib()
```
The Klayout version is 2.28.2 running on Ubuntu 22.04.

This is the error message I get if I run the script:
![image](https://user-images.githubusercontent.com/10630894/212900320-b4e6e742-a365-47e5-81e9-bb672ebd4c28.png)

Enabling and disabling the debugging mode does not change anything. The workaround is to copy the code to another editor an run it there.
Unfortunately the code is saved in xml files (.lym) so simply running the script with python is not possible.

**Comment by klayoutmatthias** [comment]
@simonwaid Thanks for these pointers. 

The problem seems to be related to Python 3.10.6 which is default on Ubuntu. With the 3.8.10 version I am using for my own builds on Ubuntu 22, everything works as expected:

![image](https://user-images.githubusercontent.com/25720841/212978470-6cf477f6-d177-43a0-9725-b72010362dfc.png)

This will give me enough pointers to debugging.

Apart from that you don't need to use the XML format. You can use plain text files too (chose "Plain Python file" for the macro template). KLayout will add some pseudo-comments at the beginning to mark such files for auto-execution on startup.

Some users reported to have used KLayout within PyCharm by configuring KLayout as the Python interpreter. I'm not a regular PyCharm user myself, so I cannot give more details as of now.

Matthias
