### ISSUE TITLE
How to use Python dependencies from a non-3.8 environment

### ISSUE THREAD

**Issue by nmoroze** [KLayout/klayout#1273]
I have a use case where it would be helpful to access third party Python packages in a KLayout script. I've looked into setting `$KLAYOUT_PYTHONPATH` or appending a path to these dependencies to `sys.path`, but I've run into issues around Python versioning. For this use case, we'd like to inject dependencies from an environment that may use any Python version >=3.6. However, since KLayout bundles a Python 3.8 interpreter, we run into issues when these dependencies are targeting a different version (in particular, with packages that include compiled code).

I was thinking it could be useful to add a switch to supply a path to a Python interpreter on the user's system rather than the bundled one (e.g. `klayout -py /usr/bin/klayout`), but I suppose this wouldn't help if the Python bindings for KLayout's API are compiled to a particular Python version anyways. I'm imagining one solution could be to compile multiple versions of the Python binding and distribute them all within the KL binary, and then have it pick the correct one on the fly when a user provides a path to their own interpreter. I'm not sure if this would be a big technical lift or add excessive overhead, though.

Do you have any thoughts on that proposal, or other ideas how to support this use case? Any insight would be appreciated - thank you very much!

**Comment by klayoutmatthias** [comment]
This is not the first time, this question arises, but the answer is still the same.

You're on Windows, I suppose.

If you're on Linux and you're using KLayout for a specific distro, KLayout shares Python with the system and every package you install there become available in KLayout.

On Windows, the packaged binaries come with their own Python and it is taken from mingw64 (msys2 in fact).

You cannot simply switch Python versions or allow the application to use different Pythons - the problem lies much deeper and in the binary compatibility between the Python interpreter and the host application. If you want to import 3rd party binary packages, they have to be made for a specific compiler/Python combination. So the compatibility matrix is not just involving Python versions, but also compilers. That makes supporting 3rd party libraries difficult on Windows.

True solutions are:

* Conda + KLayout: there are some efforts ongoing to provide KLayout as conda package (see for example https://github.com/KLayout/klayout/issues/1152). But that is a community effort and needs contributors. The basic requirements are met - like that KLayout builds with Microsoft VC++. If the package becomes reality, KLayout will share the Python environment with Anaconda. 

* Use the KLayout Python package: for batch mode applications you can start with any Python environment of your choice and import the KLayout package from PyPI. This will give you a decent subset of the classes, but not the UI.

Matthias

**Comment by nmoroze** [comment]
Hi Matthias - thank you very much for the thorough answer! I'm actually using Ubuntu, but didn't realize that KLayout was using the system Python since I generally work within virtual environments and keep my system Python pretty bare. I understand the limitations around Windows, though - I think we'll be able to come up with a workaround for our use case, thanks again for taking the time to answer the question!

**Comment by klayoutmatthias** [comment]
I see ... not the usual Windows situation :)

I understand your point about keeping a system clean. On Linux, my choice are Docker containers to isolate environments. 

Also, you can build KLayout yourself fairly easy on Linux, so that gives you a choice of the Python version you're building against.

Matthias
