### ISSUE TITLE
scripts/deploy-win-mingw.sh hangs on line 112

### ISSUE THREAD

**Issue by AeonWilliamsSpark** [KLayout/klayout#1297]
I built KLayout following the Windows MSYS2 instructions on the website. When I got to the step of making an installer, I ran the command `./scripts/deploy-win-mingw.sh` and it finished running immediately without producing output. I don't understand it all, but used echo statements to locate the issue, and found if I commented out line 112 `. ./version.sh` and ran the script, it worked as expected. Not sure if this is user error or a real issue, but wanted to share either way!

**Comment by klayoutmatthias** [comment]
I guess the problem is this statement in version.sh:

```
KLAYOUT_VERSION_REV=$(git rev-parse --short HEAD 2>/dev/null)
```

in short, it calls "git" to obtain the current revision that you are building KLayout from.

In my case, git returns without output if the work area is not a git managed one. Maybe there is something different in your case and for some reason git hangs. 

The easiest fix is to remove that call:

```
KLAYOUT_VERSION_REV=
```

You can also try to figure out the root cause by running `git rev-parse --short HEAD` in your work directory. Or you check out the source code from the desired tag, so git finds a properly installed workarea and is able to derive the revision.

The revision is used in the "About" dialog to indicate the exact source code revision.

Matthias
