### ISSUE TITLE
LVS reader for MIMCAP device seems to have an issue

### ISSUE THREAD

**Issue by FaragElsayed2** [KLayout/klayout#1319]
- For latest klayout version `klayout 0.28.6`, we have an issue related to capacitance value.

Here is an example for `cap_mim_1f0_m2m3_noshield` (1.0fF/um2 MIM capacitor).
- For  `klayout 0.28.6`: 
![image](https://user-images.githubusercontent.com/91015308/226955040-bb93ebd7-cc74-4880-bee3-9e70d9815a34.png)

- For `klayout 0.28.5`:

![image](https://user-images.githubusercontent.com/91015308/226954498-99b648bc-86dd-4b19-9965-d6aa2c78dd82.png)

**Comment by FaragElsayed2** [comment]
- You could find our testing environment [HERE](https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pv/tree/lvs_mimcap_res_efab/klayout/lvs/testing)

To test MIMCAP, you could run the following command:

```
python3 run_regression.py --device=MIMCAP --run_name=mimcap_test
```

You could find all files including results in `mimcap_test` directory

**Comment by klayoutmatthias** [comment]
Many thanks - looks like the enhanced SPICE reader does not accept the "C=..." notation for capacitor values.

I'll try to debug and fix that problem asap.

Matthias

**Comment by klayoutmatthias** [comment]
Update ... it's actually a different problem.

Inside the LVS deck you are using a kind of fallback for the device values:

```
class SubcircuitModelsReader < RBA::NetlistSpiceReaderDelegate
  def parse_element(sup, element)
    case element
    when 'C'
      super("#{sup} C=2e-16", element)
    when 'R'
      super("#{sup} R=0", element)
    else
      super
    end
  end
...
```

So in other words, the "C" element gets added a " C=2e-16" string. So for example this line

```
CI1_2_2_R0 I1_2_2_R0_TOP I1_2_2_R0_BOT cap_mim_1f0_m2m3_noshield M=1 l=50.000u w=50.000u 
+ c=2.5335p
```

eventually becomes:

```
CI1_2_2_R0 I1_2_2_R0_TOP I1_2_2_R0_BOT cap_mim_1f0_m2m3_noshield M=1 l=50.000u w=50.000u 
+ c=2.5335p C=2e-16
```

During the Spice reader update, I changed the evaluation precedence from "first taking" to "last taken" without knowing that this would make a difference here. So the value taken now is 2e-16 while it was 2.5335p before.

That implementation is consistent with ngspice:

```
ngspice 1 -> listing
	

     1 : *
     2 : .global gnd
     3 : .model cap_model c
     4 : c1 a b cap_model m=1 l=50.000u w=50.000u c=2.5335p c=2e-16
     5 : .end
ngspice 2 -> show all
 Capacitor: Fixed capacitor
     device                    c1
      model             cap_model
capacitance                 2e-16       <--- second value!
      dtemp                     0
     bv_max                     0
```

So I am not sure whether I should change this back.

Admittedly ngspice behaves differently when you have both a direct value and a parameter. Like this:

```
C2 a b cap_model 2.5335p M=1 l=50.000u w=50.000u c=2e-16
```

While ngspice uses 2.5335p, KLayout takes the "c" parameter (2e-16). So that means, in all cases, the capacitor value will be 2e-16 with the fallback you are adding. I can change this to align with ngspice, but it will not have an effect in the case of your netlists.

Maybe it is possible to modify the SubcircuitsReader implementation to add the default value only if there is no value given? I don't know the background of this implementation - do you have cases where no value is given at all?

In that case, maybe this sketch shows how to solve that issue:

```
  def parse_element(sup, element)
    begin
      super
    rescue
      case element
      when 'C'
        super("#{sup} C=2e-16", element)
      when 'R'
        super("#{sup} R=0", element)
      else
        super
      end
    end
  end
```

at least the MIMCap tests seem to pass with this patch.

Matthias

Matthias

**Comment by FaragElsayed2** [comment]
@klayoutmatthias 

Yes, exactly, we have added this custom reader for netlists that don't have `C` value.

Adding this check in the reader fixes my issue.

Thanks for your quick response.

CC @atorkmabrains

**Comment by atorkmabrains** [comment]
@klayoutmatthias Thanks for looking into this. Appreciate all the great work. 

Adding a check if exists before adding our default cap sounds like a great idea. Pointers to the most efficient way to check that would be helpful?

@FaragElsayed2 could we test out this change at our end?

**Comment by FaragElsayed2** [comment]
@atorkmabrains Yes, And I have updated it 

It's ready now
https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pv/pull/92

**Comment by atorkmabrains** [comment]
Thanks @FaragElsayed2 

And thanks @klayoutmatthias for the quick analysis
