### ISSUE TITLE
Global setting to avoid reload confirmation for watched files

### ISSUE THREAD

**Issue by adriengcql** [KLayout/klayout#1343]
The file watch mode comes very handy when editing a gds file outside of klayout. In certain cases it would be nice not to have to go back to the klayout interface to confirm the reload, i.e. bypass this dialog:
![Screenshot from 2023-04-18 15-19-07](https://user-images.githubusercontent.com/26626141/232790431-156dd230-5a5b-4b23-8ab8-ae02b9469dc8.png)

One solution might be to add an option to choose whether or not confirmation is required.
![Screenshot from 2023-04-18 15-20-53](https://user-images.githubusercontent.com/26626141/232790497-264f4293-5c0a-4142-b686-8319762c3d85.png)

**Comment by klayoutmatthias** [comment]
This option is already there ... what is the point?

**Comment by adriengcql** [comment]
> This option is already there ... what is the point?

Hello Matthias, thanks for the reply, the need is to reload the file immediately without going through the confirmation dialog. I couldn't find that option but I maybe missing something ? The screenshot might be unclear, the idea is to add an option next to the `Watch Layout Files` one.

**Comment by klayoutmatthias** [comment]
I see, but no, that feature does not work.

Reason is that you cannot tell when a file is fully written. When you detect a file update, another process may still be writing the file. While this isn't a problem with purely serial files like text files, partial layout files are usually broken. All you get are error messages in that case. Specifically if the remote process writes to a network drive.

Automatic reload does not work. I tried it. You need a separate channel to trigger the reload such as IPC through sockets or similar mechanisms.

Matthias

**Comment by adriengcql** [comment]
It makes sense indeed. IPC triggers sound like a good lead, I'll try that

**Comment by sebastian-goeldi** [comment]
Shameless plug here for [klive](https://github.com/gdsfactory/klive), since it does basically exactly what you want. It uses a TcpServer from Qt, that listens on 8082, and if you send it a json, it will reload/open the file specified there.

It's still a bit barebone (not much GUI interaction yet and  not super configurable), but does the trick for most cases I've come across. Lmk if something doesn't work or it doesn't suit your needs exactly but you think it could do so. Worst case it could serve as a source for inspiration.
