### ISSUE TITLE
Can I use klayout drc module to do PCB DRC?

### ISSUE THREAD

**Issue by gilgamsh** [KLayout/klayout#1487]

**Comment by klayoutmatthias** [comment]
Basically you can. PCB layouts you read into KLayout are normal collections of polygons. But the laws of DRC scripts in VLSI are probably different ones than in the PCB world and the DRC engine is working better on Manhattan-style layouts.

**Comment by gilgamsh** [comment]
![pcb](https://github.com/KLayout/klayout/assets/56181610/1a94652d-5b98-46bf-afb4-d72e9d4bbdf4)
 Writing a script for a shape like this (curvilinear) brings me great difficulty. Would it be a wise decision to utilize KLayout for scripting PCB DRC?

**Comment by gilgamsh** [comment]
could you give me some suggestions about this?

**Comment by chkkbim** [comment]
I suggest you post this question in the klayout forum instead of this github repo as there is no bug related to klayout code.

You can use the "Search" function to look for PCB-related questions from other users, eg : 
[https://www.klayout.de/forum/discussion/comment/9873](url)
[https://www.klayout.de/forum/discussion/2367/domain-decomposition](url)

**Comment by klayoutmatthias** [comment]
Good suggestion :)

@gilgamsh What you sketch above appears to be a plain space check. That works with rectilinear geometry too.

**Comment by gilgamsh** [comment]
Thank you very much
