### ISSUE TITLE
Layout.error_layer

### ISSUE THREAD

**Issue by lukasc-ubc** [KLayout/klayout#1549]
Hi @klayoutmatthias 

Thank you for adding [Layout.error_layer()](https://www.klayout.de/doc-qt5/code/class_Layout.html#method69), as you suggested [here](https://www.klayout.de/forum/discussion/comment/10363/#Comment_10363).

I tried to access the shapes in that layer, using begin_shapes_rec, but it returns an error

    > ly.error_layer()
    1

    > it = ly.top_cell().begin_shapes_rec(ly.error_layer())
    RuntimeError: Invalid layer index in Cell.begin_shapes_rec

Is there another way of extracting shapes from both error_layer and guiding_shape_layer?

thank you
Lukas

**Comment by klayoutmatthias** [comment]
Turns out there is an easy hack.

This is what you tried and what isn't working:

```
iter = ly.top_cell().begin_shapes_rec(ly.error_layer())
for s in iter.each():
  print(s.shape())
```

But you can explicitly instantiate the `RecursiveShapeIterator` and here there is no valid layer check:

```
iter = pya.RecursiveShapeIterator(ly, ly.top_cell(), ly.error_layer())
for s in iter.each():
  print(s.shape())
```

The functionality is the same.

But the ticket makes sense. I will include the error and guiding shape layer in the valid layer set.

Matthias
