### ISSUE TITLE
Add possibility to customize main window title

### ISSUE THREAD

**Issue by EugeneZelenko** [KLayout/klayout#1583]
Hi, Matthias!

It'll be great to have possibility to customize main window title using command line option or environment variable. Motivation for this feature came from application that uses KLayout as viewer and could launch multiple KLayout sessions, so it's hard to distinguish between different applications in task bar.

**Comment by klayoutmatthias** [comment]
I'd propose a new attribute of the `MainWindow` class which allows configuring the window title.

Currently, you can configure the layout view names differently by using something like:

```
pya.LayoutView.current().title = "ABC"
```

this will show up in the main window title like this:

![image](https://github.com/KLayout/klayout/assets/25720841/5e8ead07-c6ed-437b-9c8f-2cf66efde86e)

So that is a way to customize at least the back part of the title.

Matthias

**Comment by EugeneZelenko** [comment]
Hi, Matthias!

Sure, this will work! Title could be set in startup script (`-rm`) or synchronized in more complex scenarios like socket/pipe monitoring.

**Comment by EugeneZelenko** [comment]
Hi, Matthias!

Thank you for enhancement!
