### ISSUE TITLE
Instantation path highlight mismatch with view window

### ISSUE THREAD

**Issue by s910324** [KLayout/klayout#1804]
System : Windows 11 x64 / Ubuntu 24.02
Software : Klayout 0.28.17 - 0.29.04

Hi Matthias,

I found that the Instantation path highlight seems to having some mismatch with the view window, this seems to only occured when I selected the lowest ranked element in the whole path. 

Image below I select instance "C", which is the one on the most right side.

but the view window highlight pops up at (0, 0), which seems to be not correct.

![image](https://github.com/user-attachments/assets/7764da18-caae-4c23-8dc9-3e7c496a6dc4)

[Instantation path ABC.zip](https://github.com/user-attachments/files/16400595/Instantation.path.ABC.zip)

**Comment by klayoutmatthias** [comment]
Hi @s910324,

thanks for this nicely prepared report!

I can reproduce the problem with the instantiation path display. That is, because the "instantation path" of an instance should actually stop above the instance cell - because the instance is the object, and the path to this object is TOP-ABC. 

Currently it is included, which formally is not correct, but useful. If it is included, it should show the instance itself as the last entry.

Thanks and best regards,

Matthias
