### ISSUE TITLE
Klayout not recognizing closed polygons from DXF

### ISSUE THREAD

**Issue by ashv10** [KLayout/klayout#243]
I am trying to convert an AutoCAD DXF file into GDS2 format using KLayout, for use as a photomask. On opening the file, several lines that were connected in AutoCAD appear disconnected in Klayout and the software does not automatically recognize the closed polygons. Is there a way to auto-detect closed polygons from a DXF file?

**Comment by Kazzz-S** [comment]
Hello,

My suggestion is to set the "Merge accuracy" option shown below and attempt several times.
![KLayout243A](https://user-images.githubusercontent.com/16847255/54684004-7264f380-4b56-11e9-99f5-aabf4a80a3c0.png)

The DXF data below  **_looks_** a closed (at least, a designer believes so) quadrilateral in AutoCAD and alike, but there are gaps at three corners. I guess such a gap is very small in your case.  I have faced a similar case very often.
![KLayout243B](https://user-images.githubusercontent.com/16847255/54684164-d687b780-4b56-11e9-991e-5425aa143676.png)

If I import this DXF into KLayout with the default "Merge accuracy" option, that is, zero, it will be as below.
![KLayout243C](https://user-images.githubusercontent.com/16847255/54684232-0c2ca080-4b57-11e9-90b0-a5c0c9b91dc0.png)

Since the maximum gap is 0.2 in this case, by setting this value to "Marge accuracy," I can get a polygon as below. 
![KLayout243D](https://user-images.githubusercontent.com/16847255/54684305-49912e00-4b57-11e9-9cf9-4f950172c083.png)

The DXF file is included in the ZIP file below.
[KLayout243.zip](https://github.com/KLayout/klayout/files/2988146/KLayout243.zip)

I hope this helps you.
Regards,
Kazzz

**Comment by ashv10** [comment]
Thanks, but  that didn't fix the issue. I am still new to Klayout but if I understand correctly, shouldn't the software automatically hatch closed polygons to identify them? I have attached a file with a simple shape that I drew in AutoCAD. I opened it in Klayout using the 'merge accuracy' feature that you mentioned but I didn't see a hatched polygon like the one you've shown above.
[Klayout check.zip](https://github.com/KLayout/klayout/files/2989413/Klayout.check.zip)

**Comment by Kazzz-S** [comment]
Hi,

My initial guess was wrong.
In the DXF file, you attached, the outer rectangle is drawn with a zero-width line.
So, KLayout imports it as a Path element by default. This is the reason.
![KLayout243E](https://user-images.githubusercontent.com/16847255/54721907-9c460680-4ba6-11e9-816e-3f6fab39a6cf.png)

By setting **LINE/POLYLINE** option below, 
![KLayout243F](https://user-images.githubusercontent.com/16847255/54722020-d9aa9400-4ba6-11e9-9849-301ddc68c547.png)

You can get this.
![KLayout243G](https://user-images.githubusercontent.com/16847255/54722102-0494e800-4ba7-11e9-8a53-69c900e32028.png)

Regards,
Kazzz

**Comment by ashv10** [comment]
Thanks! That worked. 
Shouldn't the hatching be separate for the circle and the area outside it though? What I see is the same as the image you have included above - either the circle is hatched or the entire rectangle but the not the area in between the two.

**Comment by klayoutmatthias** [comment]
@kazzz: many thanks again for helping!

@ashv10: in your DXF file I see a circle and a box. That are the graphics primitives and this is exactly what KLayout gives you. If you want only the area between the circle and the box to be filled, then you should draw every boundary as polyline and use the "Merge lines with width 0 into polygons" polyline mode. If you can use hatches they may be more reliable.

In general I need to say that while DXF is nice because it offers curved lines, it's definitely the *worst* format for making masks. Except for hatches and some primitives, DXF does not have the concept of "inside" and "outside" a polygon. But that is *absolutely crucial* for masks. IMHO DXF is a too big risk to take. If you search for "DXF guidelines for photomasks" you will see a lot of material about what issues to avoid. KLayout has many options to accommodate different drawing styles, but it will never be able the guess your intentions. So check the style you want to follow, configure KLayout accordingly, set up proper drawing guidelines and stick to it. Everything else will cost you.

Matthias

**Comment by Kazzz-S** [comment]
@klayoutmatthias: This is a good opportunity for me to review various **Reader Options** provided. Your comments on DXF are educative! Let me quote them to convince my colleagues that _DXF is the worst format for making masks._

@ashv10: Here are some additional experiment results.
No.1: the same as above but circles are moved manually to show that three polygons are generated.
![KLayout243H](https://user-images.githubusercontent.com/16847255/54753587-c1795a00-4c24-11e9-84a8-9387ad5ae011.png)

No.2: the same DXF file is imported with "Merge lines with width 0 into polygons" option.
![KLayout243I](https://user-images.githubusercontent.com/16847255/54753870-727ff480-4c25-11e9-99f2-9744c670a76c.png)

No.3: importing an edited DXF file where the hatch has been removed. This must be the one you wanted.
![KLayout243J](https://user-images.githubusercontent.com/16847255/54754002-cee31400-4c25-11e9-8cd9-8c429af08447.png)

Regards,
Kazzz

**Comment by klayoutmatthias** [comment]
Hi kazz,

thanks for these tests ... actually the various options have evolved to accommodate different drawing styles. But there are too many of such styles and in some cases even the viewers get confused. 

Your material is too precious for keeping in hidden here. I'd like to cross-reference it from the forum. 

Thanks and best regards,

Matthias

**Comment by ashv10** [comment]
@Kazzz-S @klayoutmatthias : Thank you for your inputs.
That fixed the problem!

**Comment by klayoutmatthias** [comment]
Ok to close this issue?

**Comment by ashv10** [comment]
Yes.
