### ISSUE TITLE
Possibility to copy user property value

### ISSUE THREAD

**Issue by EugeneZelenko** [KLayout/klayout#382]
It'll be great to have possibility (via context menu/keyboard shortcut) to copy values from User Properties dialog executed from Object Properties dialog.

**Comment by klayoutmatthias** [comment]
Hi Eugene,

I have extended the user properties dialogue, so alternatively you can edit the properties with a text editor. This is not just faster but also allows copy and paste because it's plain text. And it has syntax highlighting :)

![image](https://user-images.githubusercontent.com/25720841/68070502-76edbd80-fd6f-11e9-99ea-df4a358ad5e6.png)

Matthias

**Comment by EugeneZelenko** [comment]
Hi, Matthias!

Thank you for so fast implementation! Sure, your design is much more flexible and convenient. I just concentrated on immediate need :-)

**Comment by klayoutmatthias** [comment]
Will be released soon with 0.26.1
