### ISSUE TITLE
Script debugger stalls on big objects

### ISSUE THREAD

**Issue by klayoutmatthias** [KLayout/klayout#526]
Problem: the debugger will display the object's "to_s" values in the variable list. Some objects (e.g. huge polygons) deliver very long strings. Generating and showing these strings will stall the debugger.

Solution is to use "repr"/"inspect" for display and stop aliasing "to_s" to "inspect" (Ruby) or "__repr__" (Python).

**Comment by thomaslima** [comment]
Hello @klayoutmatthias .

I noticed a change in behavior in python's repr in my scripts and traced back to this issue. I am not sure I understand why we changed __repr__ for python as well. Now instead of showing "(1,2)" it shows "<klayout.dbcore.Point object at 0x110237dc0>", which is much longer. Is that intentional? 

Is there any chance we can revert the repr behavior?
