### ISSUE TITLE
KLayout High Sierra QT5 wPython 3 required

### ISSUE THREAD

**Issue by vanderpol2** [KLayout/klayout#624]
![image](https://user-images.githubusercontent.com/35971367/89461720-36b5d400-d721-11ea-8bbc-46dea88dc673.png)
Can you please create an installer w Python 3 version for High Sierra. Required for SIEPIC-TOOLS . maybe Brew?
Thanks Lou.

**Comment by lukasc-ubc** [comment]
The vast majority of SiEPIC tools runs in the legacy python 2. So you could try it, and ignore the warning message for now. If you find some functionality that doesn’t work, let us know as we are developing everything for python 3 these days. 


Lukas Chrostowski
Professor, Electrical and Computer Engineering
University of British Columbia
Quantum Matter Institute
Member, College of the Royal Society of Canada
http://www.mina.ubc.ca/lukasc
http://siepic.ubc.ca
https://qmi.ubc.ca/about/directory/lukas-chrostowski

**Comment by vanderpol2** [comment]
Hi Lukas, 
Vey nice to hear from you.  I am specifically tryin to get your software operating. I am stuck at INTERCONNECT. 
I says failed to load NumPy and also it fails to find  👍this .cml file even when I navigate to it, it shows geyed out in hte menu box.
![Screen Shot 2020-08-05 at 2 05 14 PM](https://user-images.githubusercontent.com/35971367/89471065-0dea0a80-d732-11ea-9ed8-2be3d361097a.png)
![Screen Shot 2020-08-05 at 3 42 22 PM](https://user-images.githubusercontent.com/35971367/89471223-6faa7480-d732-11ea-9aa3-d9a6e2b5d721.png)
I was pretty excitedio get this far along!:
![Screen Shot 2020-08-04 at 1 15 59 PM](https://user-images.githubusercontent.com/35971367/89471290-9bc5f580-d732-11ea-8bee-f26acf55d59b.png)
![Screen Shot 2020-08-05 at 8 43 36 AM](https://user-images.githubusercontent.com/35971367/89471321-b1d3b600-d732-11ea-9460-10e580d065b1.png)
![Screen Shot 2020-08-05 at 7 41 50 AM](https://user-images.githubusercontent.com/35971367/89471340-bc8e4b00-d732-11ea-83ea-6b62e47224b8.png)

**Comment by lukasc-ubc** [comment]
Hi @vanderpol2 

To learn how to use KLayout for silicon photonics, there are two online edX courses you can consider:

- https://www.edx.org/course/photonic-integrated-circuits-1  (Aug 11)
- https://www.edx.org/course/silicon-photonics-design-fabrication-and-data-ana (September)

The screenshots above show components from a layout using the technology "EBeam", while the library being installed is from technology "GSiP".

GSiP is an example library that presently isn't complete.  I do see it is missing models, so it isn't surprising you are getting the error about missing models.   Here is a screenshot of the models that are presently included.  Note that there is no grating couplers, but there is an edge coupler.

Lastly, do you have Lumerical INTERCONNECT installed, including the Netlist import license feature?  Without it, you won't be able to do circuit simulations.

regards,
Lukas

p.s. since this is not a KLayout issue, it would be preferable to report it here: https://github.com/SiEPIC/SiEPIC-Tools/issues

![image](https://user-images.githubusercontent.com/15843200/89472415-38899280-d735-11ea-9361-f76f011c113d.png)

**Comment by vanderpol2** [comment]
Ok thank you so much, moving to SiEPC-Tools/ssues/ 
![Screen Shot 2020-08-05 at 5 20 34 PM](https://user-images.githubusercontent.com/35971367/89477160-6248b680-d741-11ea-9150-f6b5255741e9.png)
![Screen Shot 2020-08-05 at 5 27 25 PM](https://user-images.githubusercontent.com/35971367/89477164-6379e380-d741-11ea-9fa2-8c2d67b7483c.png)
![Screen Shot 2020-08-05 at 5 27 58 PM](https://user-images.githubusercontent.com/35971367/89477166-64ab1080-d741-11ea-8816-5569f16f7a8b.png)
![Screen Shot 2020-08-05 at 7 38 35 AM](https://user-images.githubusercontent.com/35971367/89477175-6b398800-d741-11ea-9fa9-b309ff707a80.png)

**Comment by vanderpol2** [comment]
![Screen Shot 2020-08-05 at 3 28 13 PM](https://user-images.githubusercontent.com/35971367/89477197-7c829480-d741-11ea-8c90-47c9d88e2113.png)

**Comment by Kazzz-S** [comment]
Hi @vanderpol2,

> Can you please create an installer w Python 3 version for High Sierra. Required for SIEPIC-TOOLS . maybe Brew?
> Thanks Lou.

I've built the second set of installers for HighSierra for testing.
Please visit https://www.dropbox.com/sh/nurelwgvu6kat2t/AACTHYczC4v3BNUTpsIGOgima?dl=0 

Maybe, ```HW-klayout-0.26.7-macOS-HighSierra-2-qt5Brew-RsysPhb37.dmg```  is the one you need.

Regards,
Kazzz-S

**Comment by vanderpol2** [comment]
Installer worked!, asked for Numpy install permission at first CTA, no
python 3 requirement error message,
Awesome so far. Thanks!!
Lou
[image: Screen Shot 2020-08-11 at 9.33.20 PM.png]

**Comment by klayoutmatthias** [comment]
Very good :)

Can I close this issue?

Thanks,

Matthias

**Comment by vanderpol2** [comment]
Yes Thank You.
Best
Lou

**Comment by thomaslima** [comment]
I am closing this since this issue was solved.
