### ISSUE TITLE
Concurrent runs of klayout is unstable

### ISSUE THREAD

**Issue by meawoppl** [KLayout/klayout#791]
I have a rather large test-suite that is a part of this project: https://github.com/meawoppl/mingds
It is a tool for creating/editing/streaming GDS in Java.

As a test-regression strategy, it uses `klayout` to perform validation of files it creates where it makes the following call:
`klayout -zz -r validation_script.py`

`validation_script.py` has the following layout:
```
import pya
layout = pya.Layout()
layout.read("gds_file_to_validate.gds")
print("SUCCESS")
```

When I run it serially over ~250 permutations of valid/invalid files it completes, specifically:
- Valid files get a 0 exit code.
- Invalid files get a non-zero
This is awesome.

When I run [these tests](https://github.com/meawoppl/mingds/blob/main/src/test/java/io/txcl/mingds/validate/KLayoutValidatorTest.java) in parallel the `klayout` binary acts a bit unpredictably, sometimes even failing on the call `klayout -h` which I use to detect if it is installed on the system.

I am happy to investigate the nature of the failures, but I am not sure where to start looking honestly...

**Comment by meawoppl** [comment]
Here are some hints from the ubuntu screens from the crash report:
![image](https://user-images.githubusercontent.com/579782/117353189-aef22700-ae64-11eb-8b7c-34a29cba64b1.png)
![image](https://user-images.githubusercontent.com/579782/117353295-cdf0b900-ae64-11eb-8f91-a601369200d4.png)
![image](https://user-images.githubusercontent.com/579782/117353344-dc3ed500-ae64-11eb-931d-d7d05a06fe83.png)
![image](https://user-images.githubusercontent.com/579782/117353555-1d36e980-ae65-11eb-8ac7-98a3c5788cb4.png)

Again the command run here was `klayout -h` but it looks like something in QT is doing a double `free()` or similar sin.

**Comment by meawoppl** [comment]
As an interesting hack-around the command `klayout -zz -h` seems to be stable under parallel execution... This feels like another hint that it could be related to the QT destructor doing something naughty.

**Comment by klayoutmatthias** [comment]
I have no idea why parallel execution of separate processes should an issue. KLayout is a normal process, no tricks played on the system. 

First of all you should use 0.26.12 which is the most stable version and check if you can reproduce the problem.

Matthias

**Comment by meawoppl** [comment]
I'll bump versions and see if it goes away.

I suspect this is a qt problem, but not sure.

**Comment by meawoppl** [comment]
This still issue still exists as of this release: https://github.com/KLayout/klayout/releases/tag/v0.27

**Comment by klayoutmatthias** [comment]
@meawoppl Thanks for trying.

Actually I don't consider 0.27 to be very stable, but anyway. The "double free" problem usually is caused by memory corruption - some invalid write or something like this. I can be detected using a memory checker like valgrind, but I don't expect you to do it.

In general I can't confirm a problem with concurrent runs - I run many processes in parallel for continuous integration on Windows, a variety of Linux derivates using Docker instances and I also use KLayout in parallel in different scenarios. I do not see such fails - at least not on the released versions. I assume there is a more basic problem. On thing I noticed is "DistroRelease Ubuntu 20.04" and "installation media Ubuntu 17.10" - maybe there is a compatibility problem? Specifically with Qt?

While stabilizing 0.27 I found and fixed a few memory corruption issues. That will go into 0.27.1. If you want you can try that once it's available, but if the root cause is from a compatibility problem, this will not help.

You can in general try to build from source (this is the best way to ensure compatibility), but there may be other options. The script you show is not using UI, so you can try using a "klayout -zz" which gives you a non-UI version. Another option is to skip the KLayout binary and use the Python module from PyPI (https://pypi.org/project/klayout/). You'd need to replace "import pya" with "import klayout.db as pya". The module provides an API subset which is usually sufficient for analysis applications.

Inside the klayout package there is also a small binary called "strmrun" which basically provides the same functionality than "klayout -zz", but without the overhead. This tool can also run DRC and LVS scripts if you need that.

Best regards,

Matthias

**Comment by meawoppl** [comment]
Thanks for the notes. The `-zz` flag seems to work well for my purposes, so I will stick with that for the time being.

On my laptop (which has a much fresher install of Ubuntu) this seems to not be an issue with the same version? I think the installation media flag is just an anchor to the original USB stick used to install Ubuntu.

This does point at some sort of QT version issue. I might probe a bit more if it comes back, but for now, lets close this.

Much thanks!
